export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS_RECIEVED = 'LOAD_PRODUCTS_RECIEVED';
export const LOAD_PRODUCTS_FETCH = 'LOAD_PRODUCTS_FETCH';


export const LOAD_PRODUCT_REQUEST = 'LOAD_PRODUCT_REQUEST';
export const LOAD_PRODUCT_RECIEVED = 'LOAD_PROUCT_RECIEVED';
export const LOAD_PRODUCT_FETCH = 'LOAD_PRODUCT_FETCH';
export const RESET_PRODUCT = 'RESET_PRODUCT';


export const LOAD_BRANDS_REQUEST = 'LOAD_BRANDS_REQUEST';
export const LOAD_BRANDS_RECIEVED = 'LOAD_BRANDS_RECIEVED';
export const LOAD_BRANDS_FETCH = 'LOAD_BRANDS_FETCH';



export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_RECIEVED = 'LOGIN_USER_RECIEVED';
export const LOGIN_USER_FETCH = 'LOGIN_USER_FETCH';
export const LOGOUT = 'LOGOUT';