export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS_RECIEVED = 'LOAD_PRODUCTS_RECIEVED';
export const LOAD_PRODUCTS_FETCH = 'LOAD_PRODUCTS_FETCH';


export const LOAD_PRODUCT_REQUEST = 'LOAD_PRODUCT_REQUEST';
export const LOAD_PRODUCT_RECIEVED = 'LOAD_PROUCT_RECIEVED';
export const LOAD_PRODUCT_FETCH = 'LOAD_PRODUCT_FETCH';
export const RESET_PRODUCT = 'RESET_PRODUCT';


export const LOAD_BRANDS_REQUEST = 'LOAD_BRANDS_REQUEST';
export const LOAD_BRANDS_RECIEVED = 'LOAD_BRANDS_RECIEVED';
export const LOAD_BRANDS_FETCH = 'LOAD_BRANDS_FETCH';


export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_RECIEVED = 'LOGIN_USER_RECIEVED';
export const LOGIN_USER_FETCH = 'LOGIN_USER_FETCH';
export const LOGOUT = 'LOGOUT';


export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_RECIEVED = 'ADD_PRODUCT_RECIEVED';
export const ADD_PRODUCT_FETCH = 'ADD_PRODUCT_FETCH';

export const REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST';
export const REMOVE_PRODUCT_RECIEVED = 'REMOVE_PRODUCT_RECIEVED';
export const REMOVE_PRODUCT_FETCH = 'REMOVE_PRODUCT_FETCH';

export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_RECIEVED = 'GET_CART_RECIEVED';
export const GET_CART_FETCH = 'GET_CART_FETCH';


export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';


export const LOAD_REVIEWS_REQUEST = 'LOAD_REVIEWS_REQUEST';
export const LOAD_REVIEWS_RECIEVED = 'LOAD_REVIEWS_RECIEVED';
export const LOAD_REVIEWS_FETCH = 'LOAD_REVIEWS_FETCH';


export const LOAD_ADDRESSES_REQUEST = 'LOAD_ADDRESSES_REQUEST';
export const LOAD_ADDRESSES_RECIEVED = 'LOAD_ADDRESSES_RECIEVED';
export const LOAD_ADDRESSES_FETCH = 'LOAD_ADDRESSES_FETCH';

export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESSS_REQUEST';
export const ADD_ADDRESS_RECIEVED = 'ADD_ADDRESSS_RECIEVED';
export const ADD_ADDRESS_FETCH = 'ADD_ADDRESSS_FETCH';


export const LOAD_CHECKOUT_REQUEST = 'LOAD_CHECKOUT_REQUEST';
export const LOAD_CHECKOUT_RECIEVED = 'LOAD_CHECKOUT_RECIEVED';
export const LOAD_CHECKOUT_FETCH = 'LOAD_CHECKOUT_FETCH';
